# Generated by Django 3.1.4 on 2021-03-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0006_studentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='facultyname',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
